jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
stages:
- compile
- test
- deploy
addons:
  sonarcloud:
    organization: gavinev98-github
    token:
      secure: 37cc29a32a05b3205a101ccb430bb108813ad27b
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: "oP95EJZl2QQNYnwpRZnbZu+nKmZZq1DqZzSk9ROOmfUEAwLIomVL4W63edzoamvgUmQ/suQquTO41k+HY2T4u4u1w6F3MzanQZsGe9mXtOE7GouURCskvbneTbOi9RAYnBjDKBZzMKCcMq0s1/TEl61xNKAeQIW7fEwIADSQHdHlFQsogjPBX7CtxsYo5pZIJG3b1RKCvmrnCIsCY4wiuR1OVLBsDImuMfjVX4dd7JigIWy3VjljVSRpmZbgemR1VPhn1Pr60ImoSo+gwg6QD5IPv+4S6H81t/msOJcaWSEHz6hmX59N/5TSlAqKakTmn16UU05OS16TG/ObwhpMLNxS9Je3TLQpTKlrGKZ6HZC/B2d/ELJpQdJclGxpEQGLB1u6Sy+6Tuf2RK81mWHAahVFBlWw2yBRuJalajBZR4vdsbMJGtRHbL2z2r/ipK5wUz1B1oiQV/G8Xey+vV0RrJVkHiHpLcanYoPSSlCgG8rBwvuU8suG/LPuNy4E3r3v+0XtIUjkE+hZQNVCy0ns5PWxRxM7eI7CciC1vETGPXJHoEiZMfft02PucnoBlHaY2LLeLAN/tPJ4sLyYCf0msXOlDOxK9MI2Tbp30rTDaI0WhFJy2qkFyE2aL4t1lCBr+Z++n2D29b1z/iRqRAlKn0lZG10Veprs75e+YJuv/y0="
    app: gavinev98/StudentListFinal