jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
stages:
- compile
- test
- deploy
addons:
  sonarcloud:
    organization: gavinev98-github
    token:
      secure: 37cc29a32a05b3205a101ccb430bb108813ad27b
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: TcRjTtyxNpzZxLrCoJ7PB8bfrAv3PjbeEFFhuD7/dCkcUgoJSPDmD4XlEp7pTaiBdCtGE5xfZ2byH58EEzROahyltzkMhZl+kkOpq+t0W6Cjio4u8J7ACxQZIWkAz7Gbq3IIVJkpO+ray3bn2+nwhuZjvM07Q4SRWHSuCc8xZXOaSetii/t4T+6kj2buVomMeZ1Yyt8XZLsVzuz9ZraQtSDzd/duH7+JMFGhYNh9s8lyJaunxEkceyiZ0FsBA0/IDlgVK3QaEMcu+SwEF2Ry2ZzXB3acuB5nNNjeSFjnotm7lxM6CrcnfLEWSN8KQgsAXqeIzCv1fzN14HmQD8FygKRXEHkBspZbPoac2vEwogRv4D80tGyKizqGVdtD/62oZNJ8qsEdTktdKg1TUXc03AO+RC5SUiut9KWfj+5MSPdi6SEdohoudUmnm6hMpOi2+KiC3sScwbro6/th7iTdhVo8tvPR+XMNLFBbu/rCXGr8elrTi76/f7FIh4cCxUvjmiWb+3ULcarCAbVAp3rXx4nkqVoiSmWXshyUQ6TI3uMDhbbC/FvA1TcjYHD2gPx90IMilvJlvZhnr5yHL4qAMEOIbvKiAwdkaLID/z9GwPRlaTCDYU+G/jJzaWs69IXB3NUQNV67RcR+jg9OlRB64mBi89rz882KA9rbwBb3U50=
