jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
stages:
- compile
- test
- deploy
addons:
  sonarcloud:
    organization: gavinev98-github
    token:
      secure: 37cc29a32a05b3205a101ccb430bb108813ad27b
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key:
    secure: KIsIRz5X/9G4UHt+J0qKiqMPGyJ5oF2wzx0wD+FFe1P8hPeP7Rpi+QBL9opTx89I4SrUOKM1OVRxtS5LuQqUuavfAXgJaE23wc9aJ89s5cNK6UaojhT5YEiNet2ARjWx/f45JMG9vSDOybBKMhaOc5fOsK9r8Z5BOQ7cfAeif8UjH0MdGuok9vQH/YqmLhVSYy+ZL52haPNgj3Q5oVmjZ99v/X+MTmV6X/SH6l74fmc3YNP0XnYJQpivIo+Th/MS0NW9lxaW5Lc7VABDL9XAjrFR9ZRyUy0a29pk9kW+8HkpQOkmjnh7+2IPAiSsaLEEBJ9k2H7DjWQWCLPkvsA3I3ddXV/+rcR+P/H9Ggr4QtAmZx5LklRL4CLKvEgeC9s0DMVsOaOnZ0uBpW2S8QDHGdnk2+S5ZOH1469L5BE7wSah36LqYE12IiH3IOMsXYWlsx1Q0QL+G27XnsTVCukERPQRefA4ygogy5TfB/2S4qnlTkymFd+0cz68ZJ3QEXdUCt/r7ptRwhE0qM7uEC3a7DDF6LeVt6I/EiRZbyeucXUclqAlcU4W+7hjnpWGEsdIwd1X1avbNDQu/PS9EflzGxtaTlFCPabaKf/mrB2txUOIxxo1yV7qjNu+LlhCuJjnbAvLmgVBDMsy3FjEuOZlrndjqmRoapF6kprWk/RD0M8=
