jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
  - docker
dist: trusty
stages:
- compile
- test
- deploy

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t docker-spring-boot .
        - docker images
        - docker tag docker-spring-boot $DOCKER_USERNAME/docker-spring-boot
        - docker push $DOCKER_USERNAME/docker-spring-boot

addons:
  sonarcloud:
    organization: gavinev98-github
    token:
      secure: 37cc29a32a05b3205a101ccb430bb108813ad27b
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

notifications:
  slack:
    secure: h2At3CNf9bPMo4JJLyASd1Zjkm+u6HrRNbpzkcfr4eAWjpjfeuyrxZbYa1cPPnV4UuNS39sHTcmzhNbmry5dSYKQXgxROHLRkGeuEDNNeLQssLDkUxaGbq4+otRNEfxC2VpQlsSsly7jO76kg/a4reArw9g9EhyoWfB7V/D07CvT2kPD8kKqsVuAOEPFqlqSWcjGmKOue7lVa2XaKc+wXGESqQ4DIIPkCACKOsQ4un8OfS/Xs/2ovyt7G1Jrr0BVSMTAw8VwE6MKi2mZ+8YhOKIsuN/3xRiG2OqS5wggowIsZrkCm5wTY/jBLLQ9Bl3uon+QsVvdPkrDc4J0+NZ4P8UuiNx0BGs7Km7a3Dh+4R/wSEEM/AdbatGAhMCjobsg16p3I1wTmpNywduwQU2y9NLiOExF1eudywTmBQpacye+d74h37kKIE8xO0Lrq0+DQqJSDAlmTENPf7hR2BQmllctm3rLlUgbSc4Oe9+c7aHDNId7ADCdakc2+RWucuyV5LycODj+MvmoK5Yj0WGtVrHm9udzf2lQKa9KI93RQMui1+neWBs1vkD7AL4k8GL7Df9JiqM5Z6USha6d59NY0mz0AHgyGw4EP2OOzdOnWTWhkrNVToaODtOo9mGdLoVdZHevlX+hhSA/eENvoEvOVoNMOzLJu8gxFqNaNFr0F6E=
deploy:
  provider: heroku
  api_key:
    secure: qFFL/zboiBgU/4XGwdzz0oaGnOfxGc08O6Sz7vmju7Yo9sMFoe11BNhrjtF2ZV7GmUDMkQm/QeBQjQpnOllsnpwm2zhJfVqiNEnQQ8+E+RDD2dRu7GfU8Tf7GvNm9/3qFFtgQRogKMcBxlmt51KxLhkTAgl7riqopnT2eMObsV9j+E4dEFyfgpEchEb+EFf1QUMgB07U+L6nFGOsfWpANn7QL4kKch5MIyCropPtqNcAkHpcyj+B9yWjkMNoyIu5a0pfKQ2D/jViGd3HeRKSv0qVH4THgNsrDWnbBd4zlg8/hOPnzrqBHwQM9KFWENZkbEJIMX/0AUBKx+q31WmTMm9DOgOPtUoCTxSzQ4XFZ/7lv5QHoV7k/XtI3XXbONk/1J4v3GOR254zfKAtgR2v264T9HwSFZQhvR37lm2iab6FTX7uzBe9mvxQr0l1aNH3M9O1cjlX12zHbqBAlvRs8J0sIX+RDqOCjSgKM4HYCYcb92HF9xLvdJkDZ83rn7L0gPxRdcACg68wR7C7HSINRGfd0CabhLgr0yiN7RwQRYYgBcMSL7r9IHCeFx0d2LUgPXYguskea7uQQcMsQ5BUkK3UbFsjOlEfXdxZ6y1YuAORcuFzgHAfsb0i5bAQcgvQE/B2wfXpE2sBKp96piLMCbygvhusrJTjkvDWMndGaRc=
  app: studentlistfinal
