jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V



addons:
  sonarcloud:
    organization: "gavinev98-github" # the key of the org you chose at step #3
    token: SONARKEY
      secure: ********* # encrypted value of your token
script:
# other script steps might be done before running the actual analysis
- sonar-scanner
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar